spring:
  cloud:
    config:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
      platform: h2
  h2:
    console:
      # H2 콘솔을 활성화
      enabled: true

server:
  shutdown: graceful